docker_users:
  - remi

docker_data_root: /srv/docker

docker_repo_root: "{{ playbook_dir }}/../../.."

compose_projects:
  - name: core
    src: "{{ docker_repo_root }}/services/docker/core"
    dest: /srv/docker/core


mqtt_user: mqtt
mqtt_password: "{{ lookup('env', 'MQTT_PASSWORD') }}"

smlight_serial_url: "tcp://10.10.40.2:6638"
z2m_network_key: "GENERATE"