- name: Set timezone
  ansible.builtin.timezone:
    name: "{{ timezone }}"

- name: Install base packages
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - git
      - unzip
      - jq
    update_cache: true
    state: present