name: Deploy

on:
  push:
    branches:
      - 'feature/**'
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: Environnement cible
        required: true
        default: test
        type: choice
        options: [test, prod]

jobs:
  deploy-test:
    name: Deploy → test
    if: github.ref != 'refs/heads/main'
    runs-on: [self-hosted, homelab]
    environment: test
    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.ANSIBLE_SSH_KEY }}

      - name: Add hosts to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H docker.test.reminat.com >> ~/.ssh/known_hosts
          ssh-keyscan -p 22222 -H haos.test.reminat.com >> ~/.ssh/known_hosts

      - name: Deploy
        env:
          BWS_ACCESS_TOKEN: ${{ secrets.BWS_ACCESS_TOKEN }}
        run: |
          cd infra/ansible
          ./deploy.sh test --skip-tags github_runner

  deploy-prod:
    name: Deploy → prod
    if: github.ref == 'refs/heads/main'
    runs-on: [self-hosted, homelab]
    environment: prod
    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.ANSIBLE_SSH_KEY }}

      - name: Add hosts to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H docker.reminat.com >> ~/.ssh/known_hosts
          ssh-keyscan -p 22222 -H haos.reminat.com >> ~/.ssh/known_hosts

      - name: Deploy
        env:
          BWS_ACCESS_TOKEN: ${{ secrets.BWS_ACCESS_TOKEN }}
        run: |
          cd infra/ansible
          ./deploy.sh prod --skip-tags github_runner
